jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Remove old apk
      run: 'rm -rf ./release/*

        '
    - continue-on-error: true
      name: Set up Gradle
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Build With Gradle
      run: 'chmod +x gradlew

        ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode
        all

        '
    - continue-on-error: true
      name: Get VerName
      run: 'echo "ver_name=$(grep ''versionName'' release/output-metadata.json | cut
        -d\" -f4)" >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Upload App To Artifact
      uses: actions/upload-artifact@v3
      with:
        name: TTS_${{ env.ver_name }}
        path: ${{ github.workspace }}/release/*
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Release
      uses: softprops/action-gh-release@d4e8205d7e959a9107da6396278b2f1f07af0f9b
      with:
        body_path: ${{ github.workspace }}/CHANGELOG.md
        draft: false
        files: ${{ github.workspace }}/release/*.apk
        name: TTS_${{ env.ver_name }}
        prerelease: false
        tag_name: ${{ env.ver_name }}
    - continue-on-error: true
      name: Git Push to release
      run: 'cd ./release

        git init

        git checkout -b release

        git config --global user.name "github-actions[bot]"

        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN
        }}@github.com/${{ github.repository }}"

        git add *.apk

        git add *.json

        git commit -m "${{ env.ver_name }}"

        git push -f -u origin release

        '
name: Build Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
