jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Remove old apk
      run: 'rm -rf ./release/*

        '
    - continue-on-error: true
      name: Set up Gradle
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Build With Gradle
      run: 'chmod +x gradlew

        ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode
        all

        '
    - continue-on-error: true
      name: Get VerName
      run: 'echo "ver_name=$(grep ''versionName'' release/output-metadata.json | cut
        -d\" -f4)" >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Upload App To Artifact
      uses: actions/upload-artifact@v3
      with:
        name: TTS_${{ env.ver_name }}
        path: ${{ github.workspace }}/release/*
name: Build Test
on:
  repository_dispatch:
    types: trigger-ga___test.yml
